import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        alignItems: 'center',
        paddingTop: 48,
        paddingBottom: 24,
    },
    appName: {
        fontSize: 28,
        fontWeight: 'bold',
        color: COLORS.secondary,
        marginTop: 8,
    },
    balanceCard: {
        backgroundColor: COLORS.surface,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 24,
        borderRadius: 24,
        alignItems: 'center',
        elevation: 4,
        shadowColor: COLORS.secondary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        borderWidth: 1,
        borderColor: COLORS.lightGray,
    },
    balanceLabel: {
        fontSize: 14,
        color: COLORS.text,
        opacity: 0.6,
        marginBottom: 8,
    },
    balanceValue: {
        fontSize: 42,
        fontWeight: 'bold',
        color: COLORS.secondary,
    },
    negativeLabel: {
        fontSize: 12,
        color: COLORS.danger,
        marginTop: 8,
        fontWeight: '600',
    },
    chartsButton: {
        backgroundColor: COLORS.primary,
        marginHorizontal: 20,
        marginBottom: 20,
        padding: 18,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        elevation: 6,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    chartsButtonText: {
        color: COLORS.secondary,
        fontSize: 18,
        fontWeight: 'bold',
    },
    transactionsContainer: {
        flex: 1,
        paddingHorizontal: 20,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.secondary,
        marginBottom: 16,
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 100,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: COLORS.secondary,
        marginTop: 16,
    },
    emptySubtext: {
        fontSize: 14,
        color: COLORS.textDim,
        marginTop: 8,
    },
    fab: {
        position: 'absolute',
        right: 20,
        bottom: 30,
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 10,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
    },
});
